In [1]:
# Import NumPy
import numpy as np

# -------------------------------
# 0-D Tensor (Scalar)
# -------------------------------
x = np.array(8)
print(x)

# Print dimensions
print(x.ndim)


# -------------------------------
# 1-D Tensor (Vector)
# -------------------------------
vec = [10, 20, 30, 40, 50]
print(vec)

# Loop through elements
x = [2, 3, 4]
for element in x:
    print(element)

# Using enumerate
x = [5, 10, 15]
for i, val in enumerate(x):
    print(f"Index {i} : {val}")


# -------------------------------
# 1-D NumPy Array Properties
# -------------------------------
x = np.array([2, 3, 4])
print(x)
print(x.ndim)
print(x.shape)


# -------------------------------
# 2-D Tensor (Matrix)
# -------------------------------
x = np.array([[2, 3, 4],
              [6, 7, 8],
              [10, 11, 12]])

print(x)
print(x.ndim)
print(x.shape)


# -------------------------------
# 3-D Tensor
# -------------------------------
x = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

print(x.ndim)
print(x.shape)


# -------------------------------
# Higher Dimensional Tensor
# -------------------------------
x = np.array([
    [[2, 3, 4], [6, 7, 8], [10, 11, 12]],
    [[2, 3, 4], [6, 7, 8], [10, 11, 12]],
    [[2, 3, 4], [6, 7, 8], [10, 11, 12]],
    [[3, 4, 5], [4, 5, 6], [6, 7, 8]]
])

print(x)
print(x.ndim)
print(x.shape)


# -------------------------------
# Random Tensor
# -------------------------------
x = np.random.rand(10, 20, 28, 1)

print(x.ndim)
print(x.shape)


# -------------------------------
# TensorFlow Example
# -------------------------------
import tensorflow as tf

string_tensor = tf.constant(["alliance", "university", "is great"])

string_length = tf.strings.length(string_tensor)

print("String lengths:", string_length.numpy())


# -------------------------------
# TensorFlow 2D Tensor
# -------------------------------
x = tf.constant([[1, 2, 3],
                 [4, 5, 6]])

print(x)


# -------------------------------
# Reshaping Tensor
# -------------------------------
x = np.array([1, 2, 3])

print(x.reshape(1, 3))  # Row vector
print(x.reshape(3, 1))  # Column vector

8
0
[10, 20, 30, 40, 50]
2
3
4
Index 0 : 5
Index 1 : 10
Index 2 : 15
[2 3 4]
1
(3,)
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]
2
(3, 3)
3
(2, 2, 3)
[[[ 2  3  4]
  [ 6  7  8]
  [10 11 12]]

 [[ 2  3  4]
  [ 6  7  8]
  [10 11 12]]

 [[ 2  3  4]
  [ 6  7  8]
  [10 11 12]]

 [[ 3  4  5]
  [ 4  5  6]
  [ 6  7  8]]]
3
(4, 3, 3)
4
(10, 20, 28, 1)
String lengths: [ 8 10  8]
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
[[1 2 3]]
[[1]
 [2]
 [3]]
